replicaCount: 5

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: "alb"
  hosts:
    - host: sourcef.us
      paths:
        - path: /
          pathType: ImplementationSpecific
